name: 01 - Building Blocks
on: 
  - workflow_dispatch

jobs:
  echo_hello: 
    runs-on: ubuntu-latest
    steps:
      - name: 'Say Hello'
        run: echo "Hello, World!"

  echo-goodbye: 
    runs-on: ubuntu-latest
    steps:
      - name: 'Success step'
        run: |
          echo "I will success"
          exit 0

      - name: 'Say goodbye'
        run: echo "Goodbye!"
