name: 07 - Using Expressions
on:
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false
          
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - if: ${{ inputs.debug == true }}
              name: ${{ inputs.debug }} Print start-up data 
              run: |
                echo "Triggered by: ${{ github.event_name }}"      
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ github.run_id }}"    
            
            - if: ${{ inputs.debug == true && github.ref == 'main' }}    
              name: ${{ inputs.debug }} Print when triggered from main
              run: echo "I was triggered from main"  
              
            - name: Greeting
              run: echo "Hello World!"   