name: 16 - Working with Environment
run-name: 16 - Working with Environment | env - ${{ inputs.target-env }} 
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

jobs:
    echo-staging:
        runs-on: ubuntu-latest
        environment: staging
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default_value' }}   
        steps:
            - name: Echo Vars
              run: |
                echo "Deploy to stating..." 
    e2e-testing:
        needs: echo-staging
        runs-on: ubuntu-latest
        steps:
            - name: E2E testing
              run: echo "E2E Testing..."            
    echo-prod:
        needs: e2e-testing
        runs-on: ubuntu-latest
        environment: prod
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default_value' }}   
        steps:
            - name: Echo Vars
              run: |
                echo "Deploy to prod..."
        
           